service: client-backend

frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
  - Effect: Allow
    Action:
      - SQS:*
    Resource: "arn:aws:sqs:us-east-1:*:*"

functions:
  send:
    handler: clientsend.send
    events:
      - http:
          path: send
          method: post
          cors: true
  receive:
    handler: clientreceive.receive
    events:
      - http:
          path: receive/{id}
          method: get
          cors: true