service: client-backend

frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
  - Effect: Allow
    Action:
      - SQS:*
    Resource: "arn:aws:sqs:us-east-1:*:*"
  - Effect: Allow
    Action:
      - LEX:*
    Resource: "arn:aws:lex:us-east-1:*:*"

functions:
  send:
    handler: clientsend.send
    events:
      - http:
          path: send
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin 
              - Access-Control-Allow-Credentials 
  receive:
    handler: clientreceive.receive
    events:
      - http:
          path: receive/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin 
              - Access-Control-Allow-Credentials          